/*
 * Created on 9 Aug 2018 ( Time 15:19:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.mmm.heroku.demo.validator;

import com.mmm.heroku.demo.entities.Lead ;
import com.mmm.heroku.demo.common.MessagesKeys;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

/**
 * Validator for entity Lead
 * 
 * @author Telosys Tools Generator
 *
 */
public class LeadValidator extends AbstractValidator<Lead>{

    @Override
    public void validateEntity(Lead entity, Errors errors) {


    }
}