/*
 * Created on 9 Aug 2018 ( Time 15:19:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.mmm.heroku.demo.repository;

import com.mmm.heroku.demo.entities.Lead ;

import org.springframework.data.repository.CrudRepository;



/**
 * Spring JPA Repository for Lead
 * 
 * @author Telosys Tools Generator
 *
 */
public interface LeadRepository extends CrudRepository<Lead, Integer> {


}