/*
 * Created on 9 Aug 2018 ( Time 15:19:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.mmm.heroku.demo.common;


/**
 * Keys constants.
 * 
 * @author Telosys Tools Generator
 *
 */
public class Constants {
	
	public final static String COMPOSITE_KEY_SEPARATOR = "|";

}