/*
 * Created on 9 Aug 2018 ( Time 15:19:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.mmm.heroku.demo.common;


/**
 * Keys constants for messages.
 * 
 * @author Telosys Tools Generator
 *
 */
public class MessagesKeys {
	
	// Keys for resources messages
	public static final String ID_MUST_DEFINE = "id.must.define";
	public static final String NOT_BLANK = "not.blank";
	
}